name = "Ez Cobblemon"
author = "fluffy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1eb16e98b6575585231dfcc6f362bcca952341e7b27abab31a1aa785feb01824"

[versions]
fabric = "0.14.22"
minecraft = "1.19.2"
