name = "Ez Cobblemon"
author = "fluffy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c97ccc444047cac642de986840d32484b362ba28d17f17b09ded0bd8201935a5"

[versions]
fabric = "0.14.22"
minecraft = "1.19.2"
